title: "KwanLam's Daily"
author: "KwanLam"
description: "音樂、數位與生活的碎片"

# 【關鍵修改 1】改成原生的 theme
theme: minima 

baseurl: "" 
url: "https://你的域名.com"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  # 【關鍵修改 2】把 jekyll-remote-theme 從這裡刪掉！

minima:
  skin: light
  social_links:
    github: kwanlam08
